### ISSUE TITLE
Source-to-score hyperlinks do not work on pages other than the first page

### ISSUE THREAD

**Issue by thSoft** [thSoft/eclipse-commons#20]
Minimal example to reproduce:

``` lilypond
\version "2.18.0"

\relative c' {
    c1 \pageBreak
    d
}
```

This regression was introduced in bef995e19318f08c5a33b8e14555cde63b483a5c.

**Comment by nittka** [comment]
I can reproduce this. Can you assign the issue to me?
The reason seems to be that all annotations are assigned page 1.
