### ISSUE TITLE
Performance regression of PDF rendering

### ISSUE THREAD

**Issue by thSoft** [thSoft/eclipse-commons#25]
In the new version of JPedal, PDF rendering takes a lot of time (e.g. displaying page 3 of score.ly in [Mendelssohn's Psalm 42](http://www.mutopiaproject.org/ftp/Mendelssohn-BartholdyF/O42/wie_der_hirsch_schreit/wie_der_hirsch_schreit-a4-pdfs.zip) takes around 60 seconds), and it is blocking the UI.

**Comment by thSoft** [comment]
It might be worth trying JPedal version 7.x, but it has breaking API changes compared to 6.x.

**Comment by nittka** [comment]
I have just tried out the old JPedal version (4.X) with the infrastructure changes made in PdfViewPage. Annotation loading is not quite as fast as with 6.X, but it is not a difference of 1:10 but rather 9:10. So if 7.X does not bring any performance improvements (which I suspect, as the lost time seems not to be in the library but rather in jfx), I would suggest to go back to the original org.jpedal wrapper.

**Comment by nittka** [comment]
Locally, JPedal 7.X is as slow as 6.X and logs additional class cast exceptions. So, I don't think this is the way to go. If we don't want to incorporate a completely different pdf library, I suggest undoing the JPedal update.
