### ISSUE TITLE
PDF hyperlink highlighting is obscured by other hyperlinks

### ISSUE THREAD

**Issue by thSoft** [thSoft/eclipse-commons#32]
![highlight](https://user-images.githubusercontent.com/118109/36155589-0df2275e-10d5-11e8-8e74-cd846a67566e.png)

**Comment by nittka** [comment]
![hyperlinkrendering](https://user-images.githubusercontent.com/2562651/36159507-2d774b04-10df-11e8-8f07-cadfd2739dc9.JPG)

This change causes very strange rendering issues with windows and should be reverted. When opening a score or when scrolling notes disapper. Only when then zooming do they reappear.

**Comment by thSoft** [comment]
Crap, transparency in SWT isn't solved in a cross-platform manner. Could you try with `SWT.TRANSPARENT | SWT.BACKGROUND`?

**Comment by nittka** [comment]
transparent|background seems to work
