### ISSUE TITLE
PDF view broken on macOS 11

### ISSUE THREAD

**Issue by thSoft** [thSoft/eclipse-commons#59]
On macOS 11 Big Sur, the PDF view displays PDFs incorrectly.

**Comment by dickvalentine** [comment]
still having this problem:
<img width="1506" alt="Screen Shot 2021-03-22 at 3 22 23 PM" src="https://user-images.githubusercontent.com/22106822/112065840-9c28ca80-8b22-11eb-8f49-a0214d2d6f23.png">

**Comment by nittka** [comment]
Note, that the issue has been addressed but that no new release has been built, yet.

**Comment by thSoft** [comment]
@dickvalentine I released a release candidate of 0.7, please Check for Updates and report whether it works for you (I tested it and works for me).

**Comment by dickvalentine** [comment]
Thanks for releasing that update, and for advising me. Eclipse's "Check for
Updates" is ineffective with respect to elysium. Marketplace offers
'remove' and 'install' each in its appropriate context. After removing and
installing elysium, yes i confirm the display works correctly in my
configuration. Thank you!
