### ISSUE TITLE
allow scrolling using keys

### ISSUE THREAD

**Issue by nittka** [thSoft/eclipse-commons#9]
PdfView should allow scrolling using arrow keys

**Comment by thSoft** [comment]
Unfortunately after changing page, keyboard scrolling sometimes does not work. This may be related to #5?

**Comment by nittka** [comment]
Keyboard scrolling is only active if the PDFView has focus. For narrowing down the problem the following info would be helpful.
How did you change the page: toolbar button or key (page up, page down, home and end keys now work as well)?
What else did you do immediately before keyboard scrolling stopped working?
If you click on the score (not on a hyperlink there), does keyboard scrolling start working again (this would indicate that something caused a focus loss)?

**Comment by thSoft** [comment]
I think I found a way to deterministically reproduce the issue: if I set a zoom level so that only vertical scrolling is possible (e.g. Fit to Width), then I can't scroll with the keyboard.

**Comment by nittka** [comment]
OK. I can reproduce this.
